language: node_js
node_js:
- 10.15.1
dist: trusty
sudo: false
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts:
  - 85.143.223.101
before_install:
- openssl aes-256-cbc -K $encrypted_5f1fe41a254e_key -iv $encrypted_5f1fe41a254e_iv
  -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/id_rsa ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: bash .travis/deploy.sh
  on:
    branch: master
